### ISSUE TITLE
No textures + No translation for Creative inventory tab

### ISSUE THREAD

**Issue by Eatham532** [Team-Remastered/End-Remastered-Fabric#1]
![image](https://user-images.githubusercontent.com/78714349/177226403-89b62e90-1304-4171-b493-ecfe2a258232.png)

Also, Don't have an imge to show but there is no translation for the crative inventory tab. The text is something like `end-remastered:tab`

**Comment by Jack-Bagel** [comment]
Fixed in the latest version of the mod (5.1.1)
