### ISSUE TITLE
Great mod!The newest zh_cn.json from 1.19.2fabric

### ISSUE THREAD

**Issue by DarkCrystalll** [Team-Remastered/End-Remastered-Fabric#3]
{
  "item.endrem.old_eye": "远古之眼",
  "item.endrem.old_eye.description": "§7§o传说这颗眼睛曾属于一只巨沙虫",

  "item.endrem.rogue_eye": "无赖之眼",
  "item.endrem.rogue_eye.description": "§7§o据说它赋予了祖先红石智慧",

  "item.endrem.nether_eye": "下界之眼",
  "item.endrem.nether_eye.description": "§7§o在下界与天界的战斗中，一个恶魔弄丢了它",

  "item.endrem.cold_eye": "寒冰之眼",
  "item.endrem.cold_eye.description": "§7§o它是冰术师灭绝之前留下的最终神器之一",

  "item.endrem.magical_eye": "魔力之眼",
  "item.endrem.magical_eye.description": "§7§o若无此眼，唤魔者无异于蝼蚁",

  "item.endrem.black_eye": "漆黑之眼",
  "item.endrem.black_eye.description": "§7§o海盗说它可以让人看到传说中的黑珍珠号",

  "item.endrem.lost_eye": "迷离之眼",
  "item.endrem.lost_eye.description": "§7§o据悉它是由最早的铁匠锻造而成的",

  "item.endrem.wither_eye": "凋零之眼",
  "item.endrem.wither_eye.description": "§7§o它见证了毁灭，也许还会见证你的事物消失",

  "item.endrem.guardian_eye": "守卫者之眼",
  "item.endrem.guardian_eye.description": "§7§o它见证了许多战士沉沦于深渊",

  "item.endrem.cursed_eye": "腐化之眼",
  "item.endrem.cursed_eye.description": "§7§o逝于孤独的贪婪国王之眼。传说它会带来无尽的财富",

  "item.endrem.exotic_eye": "异国之眼",
  "item.endrem.exotic_eye.description": "§7§o那些追随这只眼睛的人再没有回来；传言说他们找到了伟大的亚特兰蒂斯城，或者迷失了",

  "item.endrem.evil_eye": "邪恶之眼",
  "item.endrem.evil_eye.description": "§7§o据说是可以保护主人免遭厄运的圣符",

  "item.endrem.undead_eye": "亡灵之眼",
  "item.endrem.undead_eye.description": "§7§o缅怀那些在死亡中生活的人的前世",

  "item.endrem.cryptic_eye": "隐形之眼",
  "item.endrem.cryptic_eye.description": "§7§o§khttps://www.youtube.com/watch?v=dQw4w9WgXcQ",

  "item.endrem.corrupted_eye": "腐蚀之眼",
  "item.endrem.corrupted_eye.description": "§7§o贪婪的国王的眼睛在孤独中消失；传说它会给主人带来无穷的财富",

  "item.endrem.witch_eye": "女巫之眼",
  "item.endrem.witch_eye.description": "§7§o据说它看到了失传的古老酿造配方",
  "item.endrem.witch_pupil": "巫瞳",

  "item.endrem.undead_soul": "亡灵之魂",

  "block.endrem.ancient_portal_frame": "空传送门框架",

  "block.endrem.ender_eye.warning": "这只眼睛并不想被使用",
  "block.endrem.custom_eye.place": "此眼睛已放置",
  "block.endrem.custom_eye.frame_has_eye": "此框架已经有一个眼睛",

  "itemGroup.endrem.endrem_tab": "末地重制",

  "block.portal_open_sound": "传送门开启",
  "block.portal_open_sound.sub": "传送门开启",

  "advancements.main.root.title": "踏上征途",
  "advancements.main.root.description": "获得你的第一颗眼",

  "advancements.main.old_eye.title": "寻财者",
  "advancements.main.old_eye.description": "获得一颗远古之眼",

  "advancements.main.rogue_eye.title": "欢迎来到丛林",
  "advancements.main.rogue_eye.description": "获得一颗暴戾之眼",

  "advancements.main.nether_eye.title": "凝视绝望",
  "advancements.main.nether_eye.description": "获得一颗下界之眼",

  "advancements.main.cold_eye.title": "美丽冻人",
  "advancements.main.cold_eye.description": "获得一颗寒冰之眼",

  "advancements.main.corrupted_eye.title": "绿宝石护体", "%%%%%%Comment%%%%%%": "金花洒更适合...",
  "advancements.main.corrupted_eye.description": "获得一颗腐化之眼",

  "advancements.main.magical_eye.title": "堕落巫师",
  "advancements.main.magical_eye.description": "获得一颗魔力之眼",

  "advancements.main.black_eye.title": "啊, 我的船在哪？",
  "advancements.main.black_eye.description": "获得一颗漆黑之眼",

  "advancements.main.lost_eye.title": "需要地图吗？",
  "advancements.main.lost_eye.description": "获得一颗迷离之眼",

  "advancements.main.wither_eye.title": "万物凋零",
  "advancements.main.wither_eye.description": "获得一颗凋零之眼",

  "advancements.main.guardian_eye.title": "现在谁才是守卫者？",
  "advancements.main.guardian_eye.description": "获得一颗守卫者之眼",

  "advancements.main.cursed_eye.title": "一个新的保护者...",
  "advancements.main.cursed_eye.description": "获得你的第一个诅咒之眼",

  "advancements.main.witch_eye.title": "不给糖就捣蛋？",
  "advancements.main.witch_eye.description": "获得一颗女巫之眼",

  "advancements.main.evil_eye.title": "真正的祝福",
  "advancements.main.evil_eye.description": "获得你的第一只邪恶之眼",

  "advancements.main.exotic_eye.title": "亚特兰蒂斯在哪里？",
  "advancements.main.exotic_eye.description": "获得你的第一只异国之眼",

  "advancements.main.undead_eye.title": "灵魂之镜",
  "advancements.main.undead_eye.description": "获得你的第一只不死之眼",

  "advancements.main.cryptic_eye.title": "耐心是通往智慧之路",
  "advancements.main.cryptic_eye.description": "获得你的第一颗隐形之眼"
}

**Comment by Jack-Bagel** [comment]
Thank you! Will be added to the 1.21 version.
